Tables to config
maikofelix47/etl-slack-service pull request #4
Opened 2022-10-13 13:46 UTC by yannellym

Added the tables to the config file

2022-10-13 15:04 UTC, maikofelix47 requested changes
Hi. Please delete the .DS_Store file and config.json. They are not meant to be in the repository

2022-10-14 19:28 UTC, yannellym commented
deleted DS_Store file and config.json. Plus, updated the readMe to reflect config structure

2022-10-14 20:18 UTC, maikofelix47 approved these changes
LGTM

2022-10-14 20:18 UTC, maikofelix47 commented on .gitignore
> +/config.DS_Store
Remove the /config.DS_Store. Should be as below
/node_modules
/config
.DS_Store

2022-10-14 20:18 UTC, maikofelix47 commented on README.md
> +  "queueTables": {
Remove the queueTable values. Since its a template, people can have different queue tables. You can have it as shown below

"queueTables": {
    "ampath": "",
    "alupe": ""
  }
  }

2022-10-14 20:18 UTC, maikofelix47 commented on config.json
> +{
Delete this file. Its already in config folder so its a duplicate

2022-10-14 20:18 UTC, merged